blank_issues_enabled: false
contact_links:
  - name: B2S Designer community forum on vpuniverse
    url: https://vpuniverse.com/files/file/2119-b2s-designer
    about: Before adding an issue, please discuss possible solutions here.
